makefile changes to stick to same naming conventions
wavefrontHQ/wavefront-proxy pull request #706
Opened 2022-03-02 19:27 UTC by sbhakta-vmware

Makefile variables create artifacts with new filenames. 
Shuffle the variables around to have consistency in files names and docker tags we upload for GA and non-GA builds.

For example:
For proxy-snapshot (non-GA)
- docker_tag: `10.14_20220119-1538` <- comes with the timestamp at the end. [Reference](https://hub.docker.com/layers/wavefronthq/proxy-snapshot/10.14_20220119-1538/images/sha256-7caffe10964e48f16ca031f4416309d45f6b22b2f1195f4d0ba1d5162f09e978?context=explore)
- DEB/RPM: `wavefront-proxy_10.14-1_amd64.deb` <- comes with iteration "1" appended after release version. [Reference](https://packagecloud.io/wavefront/proxy-next/packages/ubuntu/bionic/wavefront-proxy_10.14-1_amd64.deb)

For proxy (GA)
- docker_tag: `10.14` <- Do not append timestamp. [Reference](https://hub.docker.com/layers/wavefronthq/proxy/10.14/images/sha256-4f02ad81a9c7946593e9cec049a021e32f96aaba3214ec7e5dfd708000966605?context=explore)
- DEB/RPM: `wavefront-proxy_10.14-1_amd64.deb` <- comes with iteration "1" appended after release version, same as non-GA. [Reference](https://packagecloud.io/wavefront/proxy/packages/ubuntu/eoan/wavefront-proxy_10.14-1_amd64.deb)

2022-03-02 19:35 UTC, joannak-vmware approved these changes

2022-03-02 19:43 UTC, laullon requested changes

2022-03-02 19:43 UTC, laullon commented on Makefile
> +	docker run -v $(shell pwd)/:/proxy proxy-linux-builder /proxy/pkg/build.sh ${VERSION} 1
Put the "1" just for GA, that way we can have multiple noGA version on packagecloud.

2022-03-02 19:49 UTC, laullon commented
Can we make all this done on the Jenkins job ? Maybe have just a DOCKER_TAG and LINUX_VERSION variables with default values (with the ts), and override then on the job.

2022-03-02 20:12 UTC, sbhakta-vmware commented
> Can we make all this done on the Jenkins job ? Maybe have just a DOCKER_TAG and LINUX_VERSION variables with default values (with the ts), and override then on the job.

Good idea. I agree. Let me update my PR.

2022-03-04 03:10 UTC, sbhakta-vmware commented
No more relevant. migrated to this - https://github.com/wavefrontHQ/wavefront-proxy/pull/707

2022-03-04 03:10 UTC, closed without merging